version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=168231923555.dkr.ecr.ap-south-1.amazonaws.com/ecs-project
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t application:latest .
      - docker tag application:latest 168231923555.dkr.ecr.ap-south-1.amazonaws.com/ecs-project:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 168231923555.dkr.ecr.ap-south-1.amazonaws.com/ecs-project:latest
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/order-service.jar

